on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish Vrite Landing Page to Cloudflare Pages
    env:
      VRITE_ACCESS_TOKEN: o3qiG1nPs_1kG17He8smz:OOdP6YHsBTUDv78dVPko5
      VRITE_CONTENT_GROUP_ID: 640b816da3d81d99daed3475
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PNPM
        uses: pnpm/action-setup@v4
      - name: Build
        run: pnpm install && pnpm run build --filter @vrite/landing-page
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: vrite-landing-page
          directory: apps/landing-page/dist
